/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_fisco_bcos_sdk_jni_utilities_tx_TransactionStructBuilderJniObj */

#ifndef _Included_org_fisco_bcos_sdk_jni_utilities_tx_TransactionStructBuilderJniObj
#define _Included_org_fisco_bcos_sdk_jni_utilities_tx_TransactionStructBuilderJniObj
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_fisco_bcos_sdk_jni_utilities_tx_TransactionStructBuilderJniObj
 * Method:    encodeTransactionDataStruct
 * Signature: (Lorg/fisco/bcos/sdk/jni/utilities/tx/TransactionData;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL
Java_org_fisco_bcos_sdk_jni_utilities_tx_TransactionStructBuilderJniObj_encodeTransactionDataStruct(
    JNIEnv*, jclass, jobject);

/*
 * Class:     org_fisco_bcos_sdk_jni_utilities_tx_TransactionStructBuilderJniObj
 * Method:    encodeTransactionDataStructToJson
 * Signature: (Lorg/fisco/bcos/sdk/jni/utilities/tx/TransactionData;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL
Java_org_fisco_bcos_sdk_jni_utilities_tx_TransactionStructBuilderJniObj_encodeTransactionDataStructToJson(
    JNIEnv*, jclass, jobject);

/*
 * Class:     org_fisco_bcos_sdk_jni_utilities_tx_TransactionStructBuilderJniObj
 * Method:    decodeTransactionDataStruct
 * Signature: (Ljava/lang/String;)Lorg/fisco/bcos/sdk/jni/utilities/tx/TransactionData;
 */
JNIEXPORT jobject JNICALL
Java_org_fisco_bcos_sdk_jni_utilities_tx_TransactionStructBuilderJniObj_decodeTransactionDataStruct(
    JNIEnv*, jclass, jstring);

/*
 * Class:     org_fisco_bcos_sdk_jni_utilities_tx_TransactionStructBuilderJniObj
 * Method:    decodeTransactionDataStructV1
 * Signature: (Ljava/lang/String;)Lorg/fisco/bcos/sdk/jni/utilities/tx/TransactionDataV1;
 */
JNIEXPORT jobject JNICALL
Java_org_fisco_bcos_sdk_jni_utilities_tx_TransactionStructBuilderJniObj_decodeTransactionDataStructV1(
    JNIEnv*, jclass, jstring);

/*
 * Class:     org_fisco_bcos_sdk_jni_utilities_tx_TransactionStructBuilderJniObj
 * Method:    calcTransactionDataStructHash
 * Signature: (ILorg/fisco/bcos/sdk/jni/utilities/tx/TransactionData;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL
Java_org_fisco_bcos_sdk_jni_utilities_tx_TransactionStructBuilderJniObj_calcTransactionDataStructHash(
    JNIEnv*, jclass, jint, jobject);

/*
 * Class:     org_fisco_bcos_sdk_jni_utilities_tx_TransactionStructBuilderJniObj
 * Method:    createEncodedTransaction
 * Signature:
 * (Lorg/fisco/bcos/sdk/jni/utilities/tx/TransactionData;Ljava/lang/String;Ljava/lang/String;ILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL
Java_org_fisco_bcos_sdk_jni_utilities_tx_TransactionStructBuilderJniObj_createEncodedTransaction(
    JNIEnv*, jclass, jobject, jstring, jstring, jint, jstring);

/*
 * Class:     org_fisco_bcos_sdk_jni_utilities_tx_TransactionStructBuilderJniObj
 * Method:    encodeTransactionStruct
 * Signature: (Lorg/fisco/bcos/sdk/jni/utilities/tx/Transaction;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL
Java_org_fisco_bcos_sdk_jni_utilities_tx_TransactionStructBuilderJniObj_encodeTransactionStruct(
    JNIEnv*, jclass, jobject);

/*
 * Class:     org_fisco_bcos_sdk_jni_utilities_tx_TransactionStructBuilderJniObj
 * Method:    encodeTransactionStructToJson
 * Signature: (Lorg/fisco/bcos/sdk/jni/utilities/tx/Transaction;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL
Java_org_fisco_bcos_sdk_jni_utilities_tx_TransactionStructBuilderJniObj_encodeTransactionStructToJson(
    JNIEnv*, jclass, jobject);

/*
 * Class:     org_fisco_bcos_sdk_jni_utilities_tx_TransactionStructBuilderJniObj
 * Method:    decodeTransactionStruct
 * Signature: (Ljava/lang/String;)Lorg/fisco/bcos/sdk/jni/utilities/tx/Transaction;
 */
JNIEXPORT jobject JNICALL
Java_org_fisco_bcos_sdk_jni_utilities_tx_TransactionStructBuilderJniObj_decodeTransactionStruct(
    JNIEnv*, jclass, jstring);

/*
 * Class:     org_fisco_bcos_sdk_jni_utilities_tx_TransactionStructBuilderJniObj
 * Method:    decodeTransactionStructV1
 * Signature: (Ljava/lang/String;)Lorg/fisco/bcos/sdk/jni/utilities/tx/Transaction;
 */
JNIEXPORT jobject JNICALL
Java_org_fisco_bcos_sdk_jni_utilities_tx_TransactionStructBuilderJniObj_decodeTransactionStructV1(
    JNIEnv*, jclass, jstring);

/*
 * Class:     org_fisco_bcos_sdk_jni_utilities_tx_TransactionStructBuilderJniObj
 * Method:    decodeTransactionStructV2
 * Signature: (Ljava/lang/String;)Lorg/fisco/bcos/sdk/jni/utilities/tx/Transaction;
 */
JNIEXPORT jobject JNICALL
Java_org_fisco_bcos_sdk_jni_utilities_tx_TransactionStructBuilderJniObj_decodeTransactionStructV2(
    JNIEnv*, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
