/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_fisco_bcos_sdk_jni_rpc_RpcJniObj */

#ifndef _Included_org_fisco_bcos_sdk_jni_rpc_RpcJniObj
#define _Included_org_fisco_bcos_sdk_jni_rpc_RpcJniObj
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_fisco_bcos_sdk_jni_rpc_RpcJniObj
 * Method:    start
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_fisco_bcos_sdk_jni_rpc_RpcJniObj_start(JNIEnv*, jobject);

/*
 * Class:     org_fisco_bcos_sdk_jni_rpc_RpcJniObj
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_fisco_bcos_sdk_jni_rpc_RpcJniObj_stop(JNIEnv*, jobject);

/*
 * Class:     org_fisco_bcos_sdk_jni_rpc_RpcJniObj
 * Method:    genericMethod
 * Signature: (Ljava/lang/String;Lorg/fisco/bcos/sdk/jni/rpc/RpcCallback;)V
 */
JNIEXPORT void JNICALL
Java_org_fisco_bcos_sdk_jni_rpc_RpcJniObj_genericMethod__Ljava_lang_String_2Lorg_fisco_bcos_sdk_jni_rpc_RpcCallback_2(
    JNIEnv*, jobject, jstring, jobject);

/*
 * Class:     org_fisco_bcos_sdk_jni_rpc_RpcJniObj
 * Method:    genericMethod
 * Signature: (Ljava/lang/String;Ljava/lang/String;Lorg/fisco/bcos/sdk/jni/rpc/RpcCallback;)V
 */
JNIEXPORT void JNICALL
Java_org_fisco_bcos_sdk_jni_rpc_RpcJniObj_genericMethod__Ljava_lang_String_2Ljava_lang_String_2Lorg_fisco_bcos_sdk_jni_rpc_RpcCallback_2(
    JNIEnv*, jobject, jstring, jstring, jobject);

/*
 * Class:     org_fisco_bcos_sdk_jni_rpc_RpcJniObj
 * Method:    genericMethod
 * Signature:
 * (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lorg/fisco/bcos/sdk/jni/rpc/RpcCallback;)V
 */
JNIEXPORT void JNICALL
Java_org_fisco_bcos_sdk_jni_rpc_RpcJniObj_genericMethod__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2Lorg_fisco_bcos_sdk_jni_rpc_RpcCallback_2(
    JNIEnv*, jobject, jstring, jstring, jstring, jobject);

/*
 * Class:     org_fisco_bcos_sdk_jni_rpc_RpcJniObj
 * Method:    call
 * Signature:
 * (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lorg/fisco/bcos/sdk/jni/rpc/RpcCallback;)V
 */
JNIEXPORT void JNICALL Java_org_fisco_bcos_sdk_jni_rpc_RpcJniObj_call(
    JNIEnv*, jobject, jstring, jstring, jstring, jstring, jobject);

/*
 * Class:     org_fisco_bcos_sdk_jni_rpc_RpcJniObj
 * Method:    sendTransaction
 * Signature:
 * (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;ZLorg/fisco/bcos/sdk/jni/rpc/RpcCallback;)V
 */
JNIEXPORT void JNICALL Java_org_fisco_bcos_sdk_jni_rpc_RpcJniObj_sendTransaction(
    JNIEnv*, jobject, jstring, jstring, jstring, jboolean, jobject);

/*
 * Class:     org_fisco_bcos_sdk_jni_rpc_RpcJniObj
 * Method:    getTransaction
 * Signature:
 * (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;ZLorg/fisco/bcos/sdk/jni/rpc/RpcCallback;)V
 */
JNIEXPORT void JNICALL Java_org_fisco_bcos_sdk_jni_rpc_RpcJniObj_getTransaction(
    JNIEnv*, jobject, jstring, jstring, jstring, jboolean, jobject);

/*
 * Class:     org_fisco_bcos_sdk_jni_rpc_RpcJniObj
 * Method:    getTransactionReceipt
 * Signature:
 * (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;ZLorg/fisco/bcos/sdk/jni/rpc/RpcCallback;)V
 */
JNIEXPORT void JNICALL Java_org_fisco_bcos_sdk_jni_rpc_RpcJniObj_getTransactionReceipt(
    JNIEnv*, jobject, jstring, jstring, jstring, jboolean, jobject);

/*
 * Class:     org_fisco_bcos_sdk_jni_rpc_RpcJniObj
 * Method:    getBlockByHash
 * Signature:
 * (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;ZZLorg/fisco/bcos/sdk/jni/rpc/RpcCallback;)V
 */
JNIEXPORT void JNICALL Java_org_fisco_bcos_sdk_jni_rpc_RpcJniObj_getBlockByHash(
    JNIEnv*, jobject, jstring, jstring, jstring, jboolean, jboolean, jobject);

/*
 * Class:     org_fisco_bcos_sdk_jni_rpc_RpcJniObj
 * Method:    getBlockByNumber
 * Signature: (Ljava/lang/String;Ljava/lang/String;JZZLorg/fisco/bcos/sdk/jni/rpc/RpcCallback;)V
 */
JNIEXPORT void JNICALL Java_org_fisco_bcos_sdk_jni_rpc_RpcJniObj_getBlockByNumber(
    JNIEnv*, jobject, jstring, jstring, jlong, jboolean, jboolean, jobject);

/*
 * Class:     org_fisco_bcos_sdk_jni_rpc_RpcJniObj
 * Method:    getBlockHashByNumber
 * Signature: (Ljava/lang/String;Ljava/lang/String;JLorg/fisco/bcos/sdk/jni/rpc/RpcCallback;)V
 */
JNIEXPORT void JNICALL Java_org_fisco_bcos_sdk_jni_rpc_RpcJniObj_getBlockHashByNumber(
    JNIEnv*, jobject, jstring, jstring, jlong, jobject);

/*
 * Class:     org_fisco_bcos_sdk_jni_rpc_RpcJniObj
 * Method:    getBlockLimit
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_fisco_bcos_sdk_jni_rpc_RpcJniObj_getBlockLimit(
    JNIEnv*, jobject, jstring);

/*
 * Class:     org_fisco_bcos_sdk_jni_rpc_RpcJniObj
 * Method:    getBlockNumber
 * Signature: (Ljava/lang/String;Ljava/lang/String;Lorg/fisco/bcos/sdk/jni/rpc/RpcCallback;)V
 */
JNIEXPORT void JNICALL Java_org_fisco_bcos_sdk_jni_rpc_RpcJniObj_getBlockNumber(
    JNIEnv*, jobject, jstring, jstring, jobject);

/*
 * Class:     org_fisco_bcos_sdk_jni_rpc_RpcJniObj
 * Method:    getCode
 * Signature:
 * (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lorg/fisco/bcos/sdk/jni/rpc/RpcCallback;)V
 */
JNIEXPORT void JNICALL Java_org_fisco_bcos_sdk_jni_rpc_RpcJniObj_getCode(
    JNIEnv*, jobject, jstring, jstring, jstring, jobject);

/*
 * Class:     org_fisco_bcos_sdk_jni_rpc_RpcJniObj
 * Method:    getSealerList
 * Signature: (Ljava/lang/String;Ljava/lang/String;Lorg/fisco/bcos/sdk/jni/rpc/RpcCallback;)V
 */
JNIEXPORT void JNICALL Java_org_fisco_bcos_sdk_jni_rpc_RpcJniObj_getSealerList(
    JNIEnv*, jobject, jstring, jstring, jobject);

/*
 * Class:     org_fisco_bcos_sdk_jni_rpc_RpcJniObj
 * Method:    getObserverList
 * Signature: (Ljava/lang/String;Ljava/lang/String;Lorg/fisco/bcos/sdk/jni/rpc/RpcCallback;)V
 */
JNIEXPORT void JNICALL Java_org_fisco_bcos_sdk_jni_rpc_RpcJniObj_getObserverList(
    JNIEnv*, jobject, jstring, jstring, jobject);

/*
 * Class:     org_fisco_bcos_sdk_jni_rpc_RpcJniObj
 * Method:    getPbftView
 * Signature: (Ljava/lang/String;Ljava/lang/String;Lorg/fisco/bcos/sdk/jni/rpc/RpcCallback;)V
 */
JNIEXPORT void JNICALL Java_org_fisco_bcos_sdk_jni_rpc_RpcJniObj_getPbftView(
    JNIEnv*, jobject, jstring, jstring, jobject);

/*
 * Class:     org_fisco_bcos_sdk_jni_rpc_RpcJniObj
 * Method:    getPendingTxSize
 * Signature: (Ljava/lang/String;Ljava/lang/String;Lorg/fisco/bcos/sdk/jni/rpc/RpcCallback;)V
 */
JNIEXPORT void JNICALL Java_org_fisco_bcos_sdk_jni_rpc_RpcJniObj_getPendingTxSize(
    JNIEnv*, jobject, jstring, jstring, jobject);

/*
 * Class:     org_fisco_bcos_sdk_jni_rpc_RpcJniObj
 * Method:    getSyncStatus
 * Signature: (Ljava/lang/String;Ljava/lang/String;Lorg/fisco/bcos/sdk/jni/rpc/RpcCallback;)V
 */
JNIEXPORT void JNICALL Java_org_fisco_bcos_sdk_jni_rpc_RpcJniObj_getSyncStatus(
    JNIEnv*, jobject, jstring, jstring, jobject);

/*
 * Class:     org_fisco_bcos_sdk_jni_rpc_RpcJniObj
 * Method:    getSystemConfigByKey
 * Signature:
 * (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lorg/fisco/bcos/sdk/jni/rpc/RpcCallback;)V
 */
JNIEXPORT void JNICALL Java_org_fisco_bcos_sdk_jni_rpc_RpcJniObj_getSystemConfigByKey(
    JNIEnv*, jobject, jstring, jstring, jstring, jobject);

/*
 * Class:     org_fisco_bcos_sdk_jni_rpc_RpcJniObj
 * Method:    getTotalTransactionCount
 * Signature: (Ljava/lang/String;Ljava/lang/String;Lorg/fisco/bcos/sdk/jni/rpc/RpcCallback;)V
 */
JNIEXPORT void JNICALL Java_org_fisco_bcos_sdk_jni_rpc_RpcJniObj_getTotalTransactionCount(
    JNIEnv*, jobject, jstring, jstring, jobject);

/*
 * Class:     org_fisco_bcos_sdk_jni_rpc_RpcJniObj
 * Method:    getGroupPeers
 * Signature: (Ljava/lang/String;Lorg/fisco/bcos/sdk/jni/rpc/RpcCallback;)V
 */
JNIEXPORT void JNICALL Java_org_fisco_bcos_sdk_jni_rpc_RpcJniObj_getGroupPeers(
    JNIEnv*, jobject, jstring, jobject);

/*
 * Class:     org_fisco_bcos_sdk_jni_rpc_RpcJniObj
 * Method:    getPeers
 * Signature: (Lorg/fisco/bcos/sdk/jni/rpc/RpcCallback;)V
 */
JNIEXPORT void JNICALL Java_org_fisco_bcos_sdk_jni_rpc_RpcJniObj_getPeers(
    JNIEnv*, jobject, jobject);

/*
 * Class:     org_fisco_bcos_sdk_jni_rpc_RpcJniObj
 * Method:    getGroupList
 * Signature: (Lorg/fisco/bcos/sdk/jni/rpc/RpcCallback;)V
 */
JNIEXPORT void JNICALL Java_org_fisco_bcos_sdk_jni_rpc_RpcJniObj_getGroupList(
    JNIEnv*, jobject, jobject);

/*
 * Class:     org_fisco_bcos_sdk_jni_rpc_RpcJniObj
 * Method:    getGroupInfo
 * Signature: (Ljava/lang/String;Lorg/fisco/bcos/sdk/jni/rpc/RpcCallback;)V
 */
JNIEXPORT void JNICALL Java_org_fisco_bcos_sdk_jni_rpc_RpcJniObj_getGroupInfo(
    JNIEnv*, jobject, jstring, jobject);

/*
 * Class:     org_fisco_bcos_sdk_jni_rpc_RpcJniObj
 * Method:    getGroupInfoList
 * Signature: (Lorg/fisco/bcos/sdk/jni/rpc/RpcCallback;)V
 */
JNIEXPORT void JNICALL Java_org_fisco_bcos_sdk_jni_rpc_RpcJniObj_getGroupInfoList(
    JNIEnv*, jobject, jobject);

/*
 * Class:     org_fisco_bcos_sdk_jni_rpc_RpcJniObj
 * Method:    getGroupNodeInfo
 * Signature: (Ljava/lang/String;Ljava/lang/String;Lorg/fisco/bcos/sdk/jni/rpc/RpcCallback;)V
 */
JNIEXPORT void JNICALL Java_org_fisco_bcos_sdk_jni_rpc_RpcJniObj_getGroupNodeInfo(
    JNIEnv*, jobject, jstring, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
