/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_fisco_bcos_sdk_jni_utilities_tx_TransactionBuilderV1JniObj */

#ifndef _Included_org_fisco_bcos_sdk_jni_utilities_tx_TransactionBuilderV1JniObj
#define _Included_org_fisco_bcos_sdk_jni_utilities_tx_TransactionBuilderV1JniObj
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_fisco_bcos_sdk_jni_utilities_tx_TransactionBuilderV1JniObj
 * Method:    createTransactionData
 * Signature:
 * (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;[BLjava/lang/String;JLjava/lang/String;Ljava/lang/String;J)J
 */
JNIEXPORT jlong JNICALL
Java_org_fisco_bcos_sdk_jni_utilities_tx_TransactionBuilderV1JniObj_createTransactionData(JNIEnv*,
    jclass, jstring, jstring, jstring, jstring, jbyteArray, jstring, jlong, jstring, jstring,
    jlong);

/*
 * Class:     org_fisco_bcos_sdk_jni_utilities_tx_TransactionBuilderV1JniObj
 * Method:    createEIP1559TransactionData
 * Signature:
 * (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;[BLjava/lang/String;JLjava/lang/String;JLjava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL
Java_org_fisco_bcos_sdk_jni_utilities_tx_TransactionBuilderV1JniObj_createEIP1559TransactionData(
    JNIEnv*, jclass, jstring, jstring, jstring, jstring, jbyteArray, jstring, jlong, jstring, jlong,
    jstring, jstring);

/*
 * Class:     org_fisco_bcos_sdk_jni_utilities_tx_TransactionBuilderV1JniObj
 * Method:    calcTransactionDataHashWithFullFields
 * Signature:
 * (ILorg/fisco/bcos/sdk/jni/utilities/tx/TransactionVersion;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;[BLjava/lang/String;JLjava/lang/String;Ljava/lang/String;JLjava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL
Java_org_fisco_bcos_sdk_jni_utilities_tx_TransactionBuilderV1JniObj_calcTransactionDataHashWithFullFields(
    JNIEnv*, jclass, jint, jobject, jstring, jstring, jstring, jstring, jbyteArray, jstring, jlong,
    jstring, jstring, jlong, jstring, jstring);

/*
 * Class:     org_fisco_bcos_sdk_jni_utilities_tx_TransactionBuilderV1JniObj
 * Method:    calcTransactionDataHashWithJson
 * Signature: (ILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL
Java_org_fisco_bcos_sdk_jni_utilities_tx_TransactionBuilderV1JniObj_calcTransactionDataHashWithJson(
    JNIEnv*, jclass, jint, jstring);

/*
 * Class:     org_fisco_bcos_sdk_jni_utilities_tx_TransactionBuilderV1JniObj
 * Method:    createSignedTransactionWithSignature
 * Signature:
 * ([BLjava/lang/String;Lorg/fisco/bcos/sdk/jni/utilities/tx/TransactionVersion;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;[BLjava/lang/String;JLjava/lang/String;Ljava/lang/String;JLjava/lang/String;Ljava/lang/String;ILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL
Java_org_fisco_bcos_sdk_jni_utilities_tx_TransactionBuilderV1JniObj_createSignedTransactionWithSignature(
    JNIEnv*, jclass, jbyteArray, jstring, jobject, jstring, jstring, jstring, jstring, jbyteArray,
    jstring, jlong, jstring, jstring, jlong, jstring, jstring, jint, jstring);

/*
 * Class:     org_fisco_bcos_sdk_jni_utilities_tx_TransactionBuilderV1JniObj
 * Method:    createSignedTransactionWithFullFields
 * Signature:
 * (JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;[BLjava/lang/String;JLjava/lang/String;Ljava/lang/String;JILjava/lang/String;)Lorg/fisco/bcos/sdk/jni/utilities/tx/TxPair;
 */
JNIEXPORT jobject JNICALL
Java_org_fisco_bcos_sdk_jni_utilities_tx_TransactionBuilderV1JniObj_createSignedTransactionWithFullFields__JLjava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2_3BLjava_lang_String_2JLjava_lang_String_2Ljava_lang_String_2JILjava_lang_String_2(
    JNIEnv*, jclass, jlong, jstring, jstring, jstring, jstring, jbyteArray, jstring, jlong, jstring,
    jstring, jlong, jint, jstring);

/*
 * Class:     org_fisco_bcos_sdk_jni_utilities_tx_TransactionBuilderV1JniObj
 * Method:    createSignedTransactionWithFullFields
 * Signature:
 * (Lorg/fisco/bcos/sdk/jni/utilities/keypair/JniKeyPair;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;[BLjava/lang/String;JLjava/lang/String;Ljava/lang/String;JILjava/lang/String;)Lorg/fisco/bcos/sdk/jni/utilities/tx/TxPair;
 */
JNIEXPORT jobject JNICALL
Java_org_fisco_bcos_sdk_jni_utilities_tx_TransactionBuilderV1JniObj_createSignedTransactionWithFullFields__Lorg_fisco_bcos_sdk_jni_utilities_keypair_JniKeyPair_2Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2_3BLjava_lang_String_2JLjava_lang_String_2Ljava_lang_String_2JILjava_lang_String_2(
    JNIEnv*, jclass, jobject, jstring, jstring, jstring, jstring, jbyteArray, jstring, jlong,
    jstring, jstring, jlong, jint, jstring);

/*
 * Class:     org_fisco_bcos_sdk_jni_utilities_tx_TransactionBuilderV1JniObj
 * Method:    createSignedEIP1559TransactionWithFullFields
 * Signature:
 * (JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;[BLjava/lang/String;JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;JILjava/lang/String;)Lorg/fisco/bcos/sdk/jni/utilities/tx/TxPair;
 */
JNIEXPORT jobject JNICALL
Java_org_fisco_bcos_sdk_jni_utilities_tx_TransactionBuilderV1JniObj_createSignedEIP1559TransactionWithFullFields__JLjava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2_3BLjava_lang_String_2JLjava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2JILjava_lang_String_2(
    JNIEnv*, jclass, jlong, jstring, jstring, jstring, jstring, jbyteArray, jstring, jlong, jstring,
    jstring, jstring, jlong, jint, jstring);

/*
 * Class:     org_fisco_bcos_sdk_jni_utilities_tx_TransactionBuilderV1JniObj
 * Method:    createSignedEIP1559TransactionWithFullFields
 * Signature:
 * (Lorg/fisco/bcos/sdk/jni/utilities/keypair/JniKeyPair;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;[BLjava/lang/String;JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;JILjava/lang/String;)Lorg/fisco/bcos/sdk/jni/utilities/tx/TxPair;
 */
JNIEXPORT jobject JNICALL
Java_org_fisco_bcos_sdk_jni_utilities_tx_TransactionBuilderV1JniObj_createSignedEIP1559TransactionWithFullFields__Lorg_fisco_bcos_sdk_jni_utilities_keypair_JniKeyPair_2Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2_3BLjava_lang_String_2JLjava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2JILjava_lang_String_2(
    JNIEnv*, jclass, jobject, jstring, jstring, jstring, jstring, jbyteArray, jstring, jlong,
    jstring, jstring, jstring, jlong, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
