/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_fisco_bcos_sdk_jni_utilities_tx_TransactionStructBuilderJniObj */

#ifndef _Included_org_fisco_bcos_sdk_jni_utilities_tx_TransactionStructBuilderJniObj
#define _Included_org_fisco_bcos_sdk_jni_utilities_tx_TransactionStructBuilderJniObj
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     org_fisco_bcos_sdk_jni_utilities_tx_TransactionStructBuilderJniObj
 * Method:    createTransactionDataStruct
 * Signature:
 * (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;J)Lorg/fisco/bcos/sdk/jni/utilities/tx/TxData;
 */
JNIEXPORT jobject JNICALL
Java_org_fisco_bcos_sdk_jni_utilities_tx_TransactionStructBuilderJniObj_createTransactionDataStruct(
    JNIEnv*, jclass, jstring, jstring, jstring, jstring, jstring, jlong);

/*
 * Class:     org_fisco_bcos_sdk_jni_utilities_tx_TransactionStructBuilderJniObj
 * Method:    destroyTransactionDataStruct
 * Signature: (Lorg/fisco/bcos/sdk/jni/utilities/tx/TxData;)V
 */
JNIEXPORT void JNICALL
Java_org_fisco_bcos_sdk_jni_utilities_tx_TransactionStructBuilderJniObj_destroyTransactionDataStruct(
    JNIEnv*, jclass, jobject);

/*
 * Class:     org_fisco_bcos_sdk_jni_utilities_tx_TransactionStructBuilderJniObj
 * Method:    encodeTransactionDataStruct
 * Signature: (Lorg/fisco/bcos/sdk/jni/utilities/tx/TxData;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL
Java_org_fisco_bcos_sdk_jni_utilities_tx_TransactionStructBuilderJniObj_encodeTransactionDataStruct(
    JNIEnv*, jclass, jobject);

/*
 * Class:     org_fisco_bcos_sdk_jni_utilities_tx_TransactionStructBuilderJniObj
 * Method:    encodeTransactionDataStructToJson
 * Signature: (Lorg/fisco/bcos/sdk/jni/utilities/tx/TxData;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL
Java_org_fisco_bcos_sdk_jni_utilities_tx_TransactionStructBuilderJniObj_encodeTransactionDataStructToJson(
    JNIEnv*, jclass, jobject);

/*
 * Class:     org_fisco_bcos_sdk_jni_utilities_tx_TransactionStructBuilderJniObj
 * Method:    decodeTransactionDataStruct
 * Signature: (Ljava/lang/String;)Lorg/fisco/bcos/sdk/jni/utilities/tx/TxData;
 */
JNIEXPORT jobject JNICALL
Java_org_fisco_bcos_sdk_jni_utilities_tx_TransactionStructBuilderJniObj_decodeTransactionDataStruct(
    JNIEnv*, jclass, jstring);

/*
 * Class:     org_fisco_bcos_sdk_jni_utilities_tx_TransactionStructBuilderJniObj
 * Method:    decodeTransactionDataStructWithJson
 * Signature: (Ljava/lang/String;)Lorg/fisco/bcos/sdk/jni/utilities/tx/TxData;
 */
JNIEXPORT jobject JNICALL
Java_org_fisco_bcos_sdk_jni_utilities_tx_TransactionStructBuilderJniObj_decodeTransactionDataStructWithJson(
    JNIEnv*, jclass, jstring);

/*
 * Class:     org_fisco_bcos_sdk_jni_utilities_tx_TransactionStructBuilderJniObj
 * Method:    calcTransactionDataStructHash
 * Signature: (ILorg/fisco/bcos/sdk/jni/utilities/tx/TxData;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL
Java_org_fisco_bcos_sdk_jni_utilities_tx_TransactionStructBuilderJniObj_calcTransactionDataStructHash(
    JNIEnv*, jclass, jint, jobject);

/*
 * Class:     org_fisco_bcos_sdk_jni_utilities_tx_TransactionStructBuilderJniObj
 * Method:    createTransactionStruct
 * Signature:
 * (Lorg/fisco/bcos/sdk/jni/utilities/tx/TxData;Ljava/lang/String;Ljava/lang/String;ILjava/lang/String;)Lorg/fisco/bcos/sdk/jni/utilities/tx/Tx;
 */
JNIEXPORT jobject JNICALL
Java_org_fisco_bcos_sdk_jni_utilities_tx_TransactionStructBuilderJniObj_createTransactionStruct(
    JNIEnv*, jclass, jobject, jstring, jstring, jint, jstring);

/*
 * Class:     org_fisco_bcos_sdk_jni_utilities_tx_TransactionStructBuilderJniObj
 * Method:    destroyTransactionStruct
 * Signature: (Lorg/fisco/bcos/sdk/jni/utilities/tx/Tx;)V
 */
JNIEXPORT void JNICALL
Java_org_fisco_bcos_sdk_jni_utilities_tx_TransactionStructBuilderJniObj_destroyTransactionStruct(
    JNIEnv*, jclass, jobject);

/*
 * Class:     org_fisco_bcos_sdk_jni_utilities_tx_TransactionStructBuilderJniObj
 * Method:    createTransaction
 * Signature:
 * (Lorg/fisco/bcos/sdk/jni/utilities/tx/TxData;Ljava/lang/String;Ljava/lang/String;ILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL
Java_org_fisco_bcos_sdk_jni_utilities_tx_TransactionStructBuilderJniObj_createTransaction(
    JNIEnv*, jclass, jobject, jstring, jstring, jint, jstring);

/*
 * Class:     org_fisco_bcos_sdk_jni_utilities_tx_TransactionStructBuilderJniObj
 * Method:    encodeTransactionStruct
 * Signature: (Lorg/fisco/bcos/sdk/jni/utilities/tx/Tx;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL
Java_org_fisco_bcos_sdk_jni_utilities_tx_TransactionStructBuilderJniObj_encodeTransactionStruct(
    JNIEnv*, jclass, jobject);

/*
 * Class:     org_fisco_bcos_sdk_jni_utilities_tx_TransactionStructBuilderJniObj
 * Method:    encodeTransactionStructToJson
 * Signature: (Lorg/fisco/bcos/sdk/jni/utilities/tx/Tx;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL
Java_org_fisco_bcos_sdk_jni_utilities_tx_TransactionStructBuilderJniObj_encodeTransactionStructToJson(
    JNIEnv*, jclass, jobject);

/*
 * Class:     org_fisco_bcos_sdk_jni_utilities_tx_TransactionStructBuilderJniObj
 * Method:    decodeTransactionStruct
 * Signature: (Ljava/lang/String;)Lorg/fisco/bcos/sdk/jni/utilities/tx/Tx;
 */
JNIEXPORT jobject JNICALL
Java_org_fisco_bcos_sdk_jni_utilities_tx_TransactionStructBuilderJniObj_decodeTransactionStruct(
    JNIEnv*, jclass, jstring);

/*
 * Class:     org_fisco_bcos_sdk_jni_utilities_tx_TransactionStructBuilderJniObj
 * Method:    decodeTransactionStructWithJson
 * Signature: (Ljava/lang/String;)Lorg/fisco/bcos/sdk/jni/utilities/tx/Tx;
 */
JNIEXPORT jobject JNICALL
Java_org_fisco_bcos_sdk_jni_utilities_tx_TransactionStructBuilderJniObj_decodeTransactionStructWithJson(
    JNIEnv*, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
