/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_fisco_bcos_sdk_jni_BcosSDKJniObj */

#ifndef _Included_org_fisco_bcos_sdk_jni_BcosSDKJniObj
#define _Included_org_fisco_bcos_sdk_jni_BcosSDKJniObj
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_fisco_bcos_sdk_jni_BcosSDKJniObj
 * Method:    create
 * Signature: (Lorg/fisco/bcos/sdk/jni/common/JniConfig;)J
 */
JNIEXPORT jlong JNICALL Java_org_fisco_bcos_sdk_jni_BcosSDKJniObj_create(JNIEnv*, jclass, jobject);

/*
 * Class:     org_fisco_bcos_sdk_jni_BcosSDKJniObj
 * Method:    start
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_fisco_bcos_sdk_jni_BcosSDKJniObj_start(JNIEnv*, jobject);

/*
 * Class:     org_fisco_bcos_sdk_jni_BcosSDKJniObj
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_fisco_bcos_sdk_jni_BcosSDKJniObj_stop(JNIEnv*, jobject);

/*
 * Class:     org_fisco_bcos_sdk_jni_BcosSDKJniObj
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_fisco_bcos_sdk_jni_BcosSDKJniObj_destroy(JNIEnv*, jobject);

/*
 * Class:     org_fisco_bcos_sdk_jni_BcosSDKJniObj
 * Method:    registerBlockNotifier
 * Signature: (Ljava/lang/String;Lorg/fisco/bcos/sdk/jni/BlockNotifier;)V
 */
JNIEXPORT void JNICALL Java_org_fisco_bcos_sdk_jni_BcosSDKJniObj_registerBlockNotifier(
    JNIEnv*, jobject, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
