/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_fisco_bcos_sdk_jni_utilities_receipt_ReceiptBuilderJniObj */

#ifndef _Included_org_fisco_bcos_sdk_jni_utilities_receipt_ReceiptBuilderJniObj
#define _Included_org_fisco_bcos_sdk_jni_utilities_receipt_ReceiptBuilderJniObj
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_fisco_bcos_sdk_jni_utilities_receipt_ReceiptBuilderJniObj
 * Method:    createReceiptData
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;J)J
 */
JNIEXPORT jlong JNICALL Java_org_fisco_bcos_sdk_jni_utilities_receipt_ReceiptBuilderJniObj_createReceiptData
  (JNIEnv *, jclass, jstring, jstring, jstring, jlong);

/*
 * Class:     org_fisco_bcos_sdk_jni_utilities_receipt_ReceiptBuilderJniObj
 * Method:    createReceiptDataWithJson
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_fisco_bcos_sdk_jni_utilities_receipt_ReceiptBuilderJniObj_createReceiptDataWithJson
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_fisco_bcos_sdk_jni_utilities_receipt_ReceiptBuilderJniObj
 * Method:    destroyReceiptData
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_fisco_bcos_sdk_jni_utilities_receipt_ReceiptBuilderJniObj_destroyReceiptData
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_fisco_bcos_sdk_jni_utilities_receipt_ReceiptBuilderJniObj
 * Method:    encodeReceiptData
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_fisco_bcos_sdk_jni_utilities_receipt_ReceiptBuilderJniObj_encodeReceiptData
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_fisco_bcos_sdk_jni_utilities_receipt_ReceiptBuilderJniObj
 * Method:    decodeReceiptDataToJsonObj
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_fisco_bcos_sdk_jni_utilities_receipt_ReceiptBuilderJniObj_decodeReceiptDataToJsonObj
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_fisco_bcos_sdk_jni_utilities_receipt_ReceiptBuilderJniObj
 * Method:    calcReceiptDataHash
 * Signature: (IJ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_fisco_bcos_sdk_jni_utilities_receipt_ReceiptBuilderJniObj_calcReceiptDataHash
  (JNIEnv *, jclass, jint, jlong);

#ifdef __cplusplus
}
#endif
#endif
