/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_fisco_bcos_sdk_jni_rpc_TarsRpcJniObj */

#ifndef _Included_org_fisco_bcos_sdk_jni_rpc_RpcServiceJniObj
#define _Included_org_fisco_bcos_sdk_jni_rpc_RpcServiceJniObj
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_fisco_bcos_sdk_jni_rpc_RpcServiceJniObj
 * Method:    sendTransaction
 * Signature:
 * (JJLjava/lang/String;Ljava/lang/String;Ljava/lang/String;[BLjava/lang/String;ILjava/lang/String;Lorg/fisco/bcos/sdk/jni/rpc/RpcCallback;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_fisco_bcos_sdk_jni_rpc_RpcServiceJniObj_sendTransaction(JNIEnv*,
    jclass, jlong, jlong, jstring, jstring, jstring, jbyteArray, jstring, jint, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
