/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_fisco_bcos_sdk_jni_utilities_signature_SignatureJniObj */

#ifndef _Included_org_fisco_bcos_sdk_jni_utilities_signature_SignatureJniObj
#define _Included_org_fisco_bcos_sdk_jni_utilities_signature_SignatureJniObj
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_fisco_bcos_sdk_jni_utilities_signature_SignatureJniObj
 * Method:    sign
 * Signature: (JLjava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jbyteArray JNICALL Java_org_fisco_bcos_sdk_jni_utilities_signature_SignatureJniObj_sign
  (JNIEnv *, jclass, jlong, jstring, jstring);

/*
 * Class:     org_fisco_bcos_sdk_jni_utilities_signature_SignatureJniObj
 * Method:    verify
 * Signature: (I[BLjava/lang/String;Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_fisco_bcos_sdk_jni_utilities_signature_SignatureJniObj_verify
  (JNIEnv *, jclass, jint, jbyteArray, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
